project_id = "katxpagyuglxooftmbnu"

[functions.flowaccount-webhook]
verify_jwt = false

[functions.import-quotations]
verify_jwt = false

[functions.telegram-alert-closed-won]
verify_jwt = false

[functions.telegram-morning-briefing]
verify_jwt = false