// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://katxpagyuglxooftmbnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthdHhwYWd5dWdseG9vZnRtYm51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4NDgwMDEsImV4cCI6MjA4NzQyNDAwMX0.JdYzLMguAriiakbECe-KSLeGwW91l_B2nAKuuqc_RSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});